var api_data = {
	"app":[
		//测试环境（此秘密只能调用直发接口）必须用我提供的以下值，不要更改
		{"AppKey":"5dca6db7-6a21-4d31-a5f8-33a24a4f5b9d","AppSecret":"b8bd24a5-35b0-4e8a-bbc0-c7458e21c7ad","url":"https://open-test.4px.com/router/api/service"},
		//生成环境（正式环境）填写自己申请的app
		{"AppKey":"6efa9a05-5e31-4d2a-9a9c-da7624627f26","AppSecret":"0b768497-0c7a-4247-a7c0-0ca20cb2ae16","url":"https://open.4px.com/router/api/service"}
	],
	"api_xms":[
		{"method":"ds.xms.order.create","v":"1.1.0","title":"ds.xms.order.create(创建直发委托单)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=2&mainId=96"},
		{"method":"ds.xms.order.get","v":"1.1.0","title":"ds.xms.order.get(查询直发委托单)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=2&mainId=98"},
		{"method":"ds.xms.order.cancel","v":"1.0.0","title":"ds.xms.order.cancel(取消直发委托单)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=2&mainId=99"},
		{"method":"ds.xms.label.get","v":"1.1.0","title":"ds.xms.label.get(获取标签)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=2&mainId=102"},
		{"method":"ds.xms.logistics_product.getlist","v":"1.0.0","title":"ds.xms.logistics_product.getlist(物流产品查询)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=2&mainId=167"},
		{"method":"ds.xms.label.getlist","v":"1.0.0","title":"ds.xms.label.getlist(批量获取标签)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=2&mainId=165"},
		{"method":"ds.xms.order.updateweight","v":"1.0.0","title":"ds.xms.order.updateweight(更新预报重)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=2&mainId=169"},
		{"method":"tr.order.tracking.get","v":"1.0.0","title":"tr.order.tracking.get(物流轨迹查询)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=6&mainId=25"}
		//直发接口,以上是比较常用的接口和版本，如有其它需求自行更改添加
	],
	"api_fb4":[
		{"method":"fu.wms.sku.newcreate","v":"1.0.0","title":"fu.wms.sku.newcreate(创建SKU (新参数对接))","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=182"},
		{"method":"fu.wms.inbound.create","v":"1.0.0","title":"fu.wms.inbound.create(创建入库委托)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=107"},
		{"method":"fu.wms.sku.getlist","v":"1.0.0","title":"fu.wms.sku.getlist(批量查询SKU)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=108"},
		{"method":"fu.wms.inbound.cancel","v":"1.0.0","title":"fu.wms.inbound.cancel(取消入库委托)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=109"},
		{"method":"fu.wms.inbound.getlist","v":"1.0.0","title":"fu.wms.inbound.getlist(批量查询入库委托)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=110"},
		{"method":"fu.wms.outbound.create","v":"1.0.0","title":"fu.wms.outbound.create(创建出库委托)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=111"},
		{"method":"fu.wms.outbound.cancel","v":"1.0.0","title":"fu.wms.outbound.cancel(取消出库委托)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=112"},
		{"method":"fu.wms.outbound.getlist","v":"1.0.0","title":"fu.wms.outbound.getlist(批量查询出库委托)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=113"},
		{"method":"fu.wms.inventory.get","v":"1.0.0","title":"fu.wms.inventory.get(库存查询)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=114"},
		{"method":"fu.wms.inventory.getlog","v":"1.0.0","title":"fu.wms.inventory.getlog(查询库存流水)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=115"},
		{"method":"fu.wms.inventory.getdetail","v":"1.0.0","title":"fu.wms.inventory.getdetail(查询库存库龄)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=116"},
		{"method":"fu.wms.sku.editpicture","v":"1.0.0","title":"fu.wms.sku.editpicture(修改SKU图片)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=117"},
		{"method":"fu.wms.inbound.getinboundlabel","v":"1.0.0","title":"fu.wms.inbound.getinboundlabel(获取入库委托标签文件)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=119"},
		{"method":"fu.wms.inbound.uploadinvoicefile","v":"1.0.0","title":"fu.wms.inbound.uploadinvoicefile(上传箱单发票)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=120"},
		{"method":"fu.wms.shipment.create","v":"1.0.0","title":"fu.wms.shipment.create(创建派送委托)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=176"},
		{"method":"fu.wms.sku.edit","v":"1.0.0","title":"fu.wms.sku.edit(修改SKU信息/添加国家信息)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=195"},
		{"method":"fu.wms.plancode.getlist","v":"1.0.0","title":"fu.wms.plancode.getlist(批量查询物流计划)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=198"},
		{"method":"com.basis.external.create","v":"1.0.0","title":"com.basis.external.create(创建LMA订单)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=200"},
		{"method":"com.basis.external.getLabel","v":"1.0.0","title":"com.basis.external.getLabel(获取LMA面单)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=201"},
		{"method":"com.basis.external.cancelLabel","v":"1.0.0","title":"com.basis.external.cancelLabel(取消LMA订单)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=1&mainId=202"}
		//{"method":"xxxxx","v":"1.0.0","title":"xxxxxxx","url":"xxxxx"},
		//仓发接口,以上是比较常用的接口和版本，如有其它需求自行更改添加
	],
		"api_pub":[
		{"method":"com.basis.declare.create","v":"1.0.0","title":"com.basis.declare.create(创建申报产品)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=121"},
		{"method":"com.basis.declare.getlist","v":"1.0.0","title":"com.basis.declare.getlist(批量查询申报产品)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=122"},
		{"method":"com.basis.declare.skubinddeclare","v":"1.0.0","title":"com.basis.declare.skubinddeclare(申报产品关联SKU)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=123"},
		{"method":"com.basis.declare.edit","v":"1.0.0","title":"com.basis.declare.edit(修改申报产品)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=124"},
		{"method":"com.basis.measureunit.getlist","v":"1.0","title":"com.basis.measureunit.getlist(查询计量单位)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=125"},
		{"method":"com.basis.logistics_product.getlist","v":"1.0.0","title":"com.basis.logistics_product.getlist(查询物流产品信息)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=127"},
		{"method":"com.basis.declare.getcategory","v":"1.0.0","title":"com.basis.declare.getcategory(查询申报产品种类)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=128"},
		{"method":"com.css.price_calculator","v":"1.0.0","title":"com.css.price_calculator(费用试算(测试))","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=144"},
		{"method":"com.basis.warehouse.getlist","v":"1.1.0","title":"com.basis.warehouse.getlist(查询仓库信息)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=153"},
		{"method":"com.basis.billing.getbilling","v":"1.0.0","title":"com.basis.billing.getbilling(费用查询)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=159"},
		{"method":"com.basis.declare.countrybinddeclare","v":"1.0.0","title":"com.basis.declare.countrybinddeclare(申报产品绑定国家)","url":"http://open.4px.com/apiInfo/apiDetail?itemId=8&mainId=161"},
		//公共服务,以上是比较常用的接口和版本，如有其它需求自行更改添加
	]
	
}